- ayasuna.utilities.prepare_arguments:
    specification: "{{ (lookup('ansible.builtin.file', role_path + '/meta/argument_specs.yml') | from_yaml)['argument_specs']['build'] }}"
  register: ayasuna__utilities__ingot__privates__build_arguments
  tags:
    - "ayasuna__utilities__ingot"
    - "ayasuna__utilities__ingot@build"

- name: "[Build] Including tasks from build/main.yml to build the ingot"
  ansible.builtin.include_tasks:
    file: "build/main.yml"
    apply:
      tags:
        - "ayasuna__utilities__ingot"
        - "ayasuna__utilities__ingot@build"
  tags:
    - "ayasuna__utilities__ingot"
    - "ayasuna__utilities__ingot@build"