- name: "[Hostname] Preparing arguments"
  ayasuna.utilities.prepare_arguments:
    specification: "{{(lookup('ansible.builtin.file', role_path + '/meta/argument_specs.yml') | from_yaml)['argument_specs']['hostname']}}"
  register: ayasuna__utilities__host__privates__arguments
  tags:
    - "ayasuna__utilities__host"
    - "ayasuna__utilities__host@hostname"

- name: "[Hostname] Including tasks from hostname/main.yml to set the hostname"
  ansible.builtin.include_tasks:
    file: "hostname/main.yml"
    apply:
      tags:
        - "ayasuna__utilities__host"
        - "ayasuna__utilities__host@hostname"
  tags:
    - "ayasuna__utilities__host"
    - "ayasuna__utilities__host@hostname"