- name: "[Packages] Preparing arguments"
  ayasuna.utilities.prepare_arguments:
    specification: "{{(lookup('ansible.builtin.file', role_path + '/meta/argument_specs.yml') | from_yaml)['argument_specs']['packages']}}"
  register: ayasuna__utilities__host__privates__arguments
  tags:
    - "ayasuna__utilities__host"
    - "ayasuna__utilities__host@packages"

- name: "[Packages] Including tasks from packages/main.yml to upgrade system & install packages"
  ansible.builtin.include_tasks:
    file: "packages/main.yml"
    apply:
      tags:
        - "ayasuna__utilities__host"
        - "ayasuna__utilities__host@packages"
  tags:
    - "ayasuna__utilities__host"
    - "ayasuna__utilities__host@packages"